version: "3.6"

services:
  traefik:
    image: traefik:v2.4.14
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik/


  # a test service run on 8002
  whoami:
    image: traefik/whoami
    container_name: "whoami"
    labels:
      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"    