version: "2"

services:
  traefik:
    image: traefik:v2.5
    container_name: "traefik"
    hostname: "traefik"
    command: 
      --api.insecure=true 
      --providers.docker  
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik/

  # whoami:
  #   image: "containous/whoami"
  #   container_name: "whoami"
  #   hostname: "whoami"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Path(`/whoami`)"      