## STATIC CONFIGURATION
log:
  level: INFO

pilot:
    token: "82ae5729-835c-464c-87e3-8d621622c1d8"

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  web:
    address: ":8002"

providers:
  file:
    filename: "/etc/traefik/traefik.yaml"
  docker:
    endpoint: "unix:///var/run/docker.sock"

experimental:
  devPlugin:
    goPath: /etc/traefik
    moduleName: github.com/1340908470/casdoorauth

## DYNAMIC CONFIGURATION
http:
  routers:
    route-whoami:
      rule: "Path(`/whoami`) || Path(`/callback`)"
      service: route-whoami-service
      middlewares:
        - plugindemo
      priority: 1000
      entryPoints:
        - http

  services:
    route-whoami-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8002"

  middlewares:
    plugindemo:
      plugin:
        dev:
          RedirectURI: https://oa.casbin.com/callback    
          ClientID: 0ba528121ea87b3eb54d
          ServiceHost: https://door.casbin.com